### ISSUE TITLE
[feature request]缺失的数据类型及其图表化

### ISSUE THREAD

**Issue by Rictusempra** [WangDaYeeeeee/GeometricWeather#11]
1.缺失的数据类型：降水量 降水概率 云层覆盖率 日照时间
2.将这些数据跟现有图表整合 建议参考 https://play.google.com/store/apps/details?id=com.morecast.weather

**Comment by WangDaYeeeeee** [comment]
降水概率是有的，每日的和小时的都有，可以点击趋势图的天气图标，在弹窗里查看，小时趋势图中如果降水概率大于0，会以柱状图的形式显示在表里。

日照时间如果是单纯的日落日出间隔，我会添加。

其他两项我也没办法。。。

EMLVIRUS <notifications@github.com>于2017年2月16日周四 15:48写道：

**Comment by EMLVIRUS** [comment]
那这是bug咩 还是凡是阵雨 都在图表中默认为0
![image](https://cloud.githubusercontent.com/assets/16912240/23012472/6630148a-f461-11e6-8055-c1ede12f1a83.png)

**Comment by WangDaYeeeeee** [comment]
单日预报的折线图中不显示概率，只会在小时预报里显示

EMLVIRUS <notifications@github.com>于2017年2月16日周四 16:03写道：

**Comment by EMLVIRUS** [comment]
> 小时趋势图中如果降水概率大于 0，会以柱状图的形式显示在表里。

能否像这样把降水概率也加到逐日预报图表中

**Comment by WangDaYeeeeee** [comment]
尝试过，会有点乱，我还在想有没有更好的办法，其实也不是很有必要，一般如果有雨都会看得出来

EMLVIRUS <notifications@github.com>于2017年2月16日周四 16:10写道：

**Comment by EMLVIRUS** [comment]
我一开始给的那个链接的应用就是一个解决办法......................

**Comment by WangDaYeeeeee** [comment]
他那个也是挺复杂的，我在看看吧
