### ISSUE TITLE
功能请求

### ISSUE THREAD

**Issue by WhiCCX0** [WangDaYeeeeee/GeometricWeather#110]
请求大大增加上一周的天气显示（历史天气）方便感知天气变化

**Comment by WangDaYeeeeee** [comment]
有昨日气温

WhiCCX0 <notifications@github.com>于2019年12月14日 周六21:32写道：

**Comment by WhiCCX0** [comment]
蛤？我怎么没有发现啊

**Comment by WangDaYeeeeee** [comment]
仔细看看，横线

WhiCCX0 <notifications@github.com>于2019年12月14日 周六21:48写道：

**Comment by WhiCCX0** [comment]
强大啊，这个实现方式属实🐮批，之前愣是没有发现。。
