### ISSUE TITLE
通知文字

### ISSUE THREAD

**Issue by WhiCCX0** [WangDaYeeeeee/GeometricWeather#114]
预警通知文字显示不完全，也无法下拉查看完全
![Screenshot_20191230-080012](https://user-images.githubusercontent.com/47388635/71591407-2627f480-2b67-11ea-8f0b-6a1eb67970cb.jpg)

**Comment by WangDaYeeeeee** [comment]
会想想办法，但是预警一般字数都比较多，而且还经常一次推送几条，所以通知也倾向于展示个大概
