### ISSUE TITLE
Precipitation probability

### ISSUE THREAD

**Issue by sodqeyounes** [WangDaYeeeeee/GeometricWeather#117]
![IMG_20200112_155537](https://user-images.githubusercontent.com/8031530/72219921-007df080-3554-11ea-9906-c0e6804adf62.jpg)
Hi, I think that I found an issue with **Precipitation Probability**. Why **Total** doesn't equal the sum of **rain precipitation** + **snow precipitation**?

**Comment by infinitewaveparticle** [comment]
If there was a 75% chance of rain and a 50% chance of snow on the same day the chance of ANY precipitation would not be 125% - it would actually be the average of the 2 values.

**Comment by infinitewaveparticle** [comment]
A = probability of snow as a decimal
B = probability of rain as a decimal
There are 4 possible events:

1) Neither:
P1 = (1-A)*(1-B)
2) Snow only
P2 = A*(1-B)
3) Rain only
P3 = B*(1-A)
4) Both
P4 = A*B

So to accurately assess the chance of EITHER (total chance of precipitation) we must add P2 + P3

In the example with A = 0.41 and B = 0.02:
P2 = 0.41 * (0.98) = 0.4018
P3 = 0.02 * (0.59) = 0.0118
P2 + P3 = 0.4136, or 41.36%

If rounded down then 41% is correct.

**Comment by infinitewaveparticle** [comment]
You could also add the chance of both happening at the same time (P4) = 0.0082, which would make the total 0.4218, or 42%
