### ISSUE TITLE
[feature reqeust]自定义数据刷新间隔

### ISSUE THREAD

**Issue by Rictusempra** [WangDaYeeeeee/GeometricWeather#12]
RT

**Comment by WangDaYeeeeee** [comment]
会添加

EMLVIRUS <notifications@github.com>于2017年2月16日周四 16:08写道：

**Comment by EMLVIRUS** [comment]
5.27 添加的选项令人感到混淆 因为
1. 假如是1小时 1小时30分钟 2小时...  那么 这个间隔对于有些用户明显过长 有些选项也没有必要 建议参考雅虎的方案：10分钟 15分钟 30分钟 1小时 2小时 3小时等
2.假如是1分钟...... 那么......
