### ISSUE TITLE
[Feature Request] Weather Radar Map

### ISSUE THREAD

**Issue by sn0ot** [WangDaYeeeeee/GeometricWeather#139]

**Comment by WangDaYeeeeee** [comment]
No such plan in the short term, because there is not a suitable service
provider right now.

sn0ot <notifications@github.com> 于2020年5月23日周六 上午7:18写道：

**Comment by rhjdvsgsgks** [comment]
hi
i found a weather map provider [here](https://openweathermap.org/api/weathermaps) and it seems free

**Comment by WangDaYeeeeee** [comment]
I'll check that.~👌
