### ISSUE TITLE
[Feature Request] Refresh when opening app

### ISSUE THREAD

**Issue by SRTRVTH** [WangDaYeeeeee/GeometricWeather#143]
Of course, fantastic work with the app!

As stated in the title, it would be incredibly convenient if there was an option for the data to be refreshed as soon as the app is opened rather than having to refresh manually or hope the data was refreshed recently.

**Comment by WangDaYeeeeee** [comment]
When the app is started, it will first check the timestamp of the current weather cache. If the time exceeds the background refresh interval, app will automatically refresh the weather data.
