### ISSUE TITLE
耗电异常高

### ISSUE THREAD

**Issue by cheetah747** [WangDaYeeeeee/GeometricWeather#15]
没刷几次数据，但耗电的占比却居高不下，仅次于浏览器。

**Comment by cheetah747** [comment]
以前用的别的天气几乎进不了系统设置的耗电排行榜。

**Comment by WangDaYeeeeee** [comment]
第一次得到这样的反馈，我自己使用是正常的，1%左右

不知道你有没有开启常驻后台，未打开常驻后台是通过定时任务进行刷新的，有些ROM可能会出现bug，重装试试吧，尽量开启常驻后台

**Comment by EMLVIRUS** [comment]
![](http://i.imgur.com/E9Cvxsw.png)
