### ISSUE TITLE
Weather API Question

### ISSUE THREAD

**Issue by CorvetteCole** [WangDaYeeeeee/GeometricWeather#152]
Hey there, how do you afford to pay for the AccuWeather API? I've been developing a watch face that uses weather and I couldn't get around charging people for API access.

Thanks

**Comment by JamesDean829** [comment]
This is not "an issue". For those questions a personal message is more suitable.

**Comment by maityamit** [comment]
Please do not spam @CorvetteCole Because this is not an issue

**Comment by CorvetteCole** [comment]
where did you guys come from? been a year and now two people are jumping on me for this? lol
