### ISSUE TITLE
Feature Revision Request

### ISSUE THREAD

**Issue by ImAgoodGirlSumtimz** [WangDaYeeeeee/GeometricWeather#153]
Hi, is it possible for the Precipitation Forecast alert to state during which hour(s) the rain is expected, instead of staying it will start in the next couple of hours? Thank you.  :)

**Comment by Maciejfiedler** [comment]
Ok

**Comment by WangDaYeeeeee** [comment]
Sorry to reply to you so late, this feature is limited by the data provided by weather source and cannot be particularly accurate.
