### ISSUE TITLE
[Design Refinement] Dialog Corner Radius

### ISSUE THREAD

**Issue by Domi04151309** [WangDaYeeeeee/GeometricWeather#155]
The main cards for the weather use rounded corners with a specific corner radius. It would be nice if the detailed dialogs would use the same corner radius. The `dialogCornerRadius` attr from `AppCompat` can be used in the app's `styles` for this.

### Current Dialog with lower corner radius
![Screenshot_20200812-163651](https://user-images.githubusercontent.com/36272047/90029132-c7a92400-dcba-11ea-829d-7e40a8e59291.jpg)

**Comment by WangDaYeeeeee** [comment]
👌     GOT IT BRO.
