### ISSUE TITLE
[bug report] different appearance on same weather with different service provider

### ISSUE THREAD

**Issue by rhjdvsgsgks** [WangDaYeeeeee/GeometricWeather#158]
is it a bug ?
caiyun
![a](https://user-images.githubusercontent.com/26178113/90630641-ece4e780-e210-11ea-980b-2a7bc911cc7b.png)
accuweather
![b](https://user-images.githubusercontent.com/26178113/90630646-efdfd800-e210-11ea-9062-02efbd5469ad.png)

different appearance appeared on same weather , same location and same time with different service provider

**Comment by WangDaYeeeeee** [comment]
天气源会返回天气的代码和文字说明，有时候文字说明和代码对不上就会出现这样的问题，这个应该是数据源的问题
