### ISSUE TITLE
Humidity alerts 

### ISSUE THREAD

**Issue by robsonsobral** [WangDaYeeeeee/GeometricWeather#160]
Hi!

Could, please, add low air humidity alerts?

Thank you!

**Comment by MD77MD** [comment]
this would be very useful

**Comment by WangDaYeeeeee** [comment]
Sorry for the late reply.
It sounds like a good idea, and it seems that other conditions can also be added.

**Comment by MD77MD** [comment]
> Sorry for the late reply.
> It sounds like a good idea, and it seems that other conditions can also be added.

yesssss... im glad you like it... just additional ideas, 
their could be alerts for: 
1. max temp/hum, mini temp/hum 
2. max wind also mini wind could be useful if someone wants to go out
3. max uv
4. rain... etc.

also the alert system could be implemented as a trigger and alert thus when a certain value is meet an alert is triggered eg:
- alert if  {temp} is {greater} then {35°} 

better yet if alerts could be triggered when a combination of conditions are meet. this would be great for planning, such as going on a trip or staying at home for a family game. eg:
- alert if {temp} is {lesser} then {28} **and** {wind} is {lesser} then {5m/s gentle breeze} **and** {UV index} is {lesser} then {7 high}

this would be great day to plan an picnic/outing⛱️🏕️
adding to that, a description next to values could be added eg. in UV index, the drop down menu could have these values:
- 3 low
- 4
- 5 medium
- 6 
- 7 high 

this could be used to describe all drop down menu values such as cloud coverage (partially sunny, cloudy), humidity levels, wind speed etc.

Also non-numerical values could be added such as (sunny, cloudy) if they are standardized. however, this is less useful if descriptions are added next to drop down menu is added like I explained above.
- alert if  {temp} is {greater} then {25°} **and** {sky} is {cloudy}. 

Moreover, alerts could be done in advance. using the advice example: alert {one day before} if  {temp} is {greater} then {35°}. values could be (same day, one day before, two days before, three days before...etc.) up to the maximum days forecasted.

I know this is alot to ask, but this could be the differentiation factor of your app that makes it stand out.

P.S: I'm not a codder but I'm willing to help with any tests you need.
