### ISSUE TITLE
老师，桌面插件问题

### ISSUE THREAD

**Issue by SoyKoa** [WangDaYeeeeee/GeometricWeather#166]
老师，桌面插件风况这里，能不能优化成调用后台实时数据，西北风二级，北风一级，东南风三级....更加详细的呢？那样更直观些　　　可以把“风况”2个字删掉
![1111](https://user-images.githubusercontent.com/76244289/102685216-0414ff80-421a-11eb-9b21-7200a23c53c0.jpg)

**Comment by WangDaYeeeeee** [comment]
下版本会更改，好主意！
