### ISSUE TITLE
Screenshots for F-Droid

### ISSUE THREAD

**Issue by mondlicht-und-sterne** [WangDaYeeeeee/GeometricWeather#168]
You can add Screenshots for F-Droid, too, if you want.

https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/

https://gitlab.com/snippets/1895688

**Comment by papjul** [comment]
The F-Droid release is maintained in this fork: https://github.com/geometric-weather-foss/GeometricWeather

However, screenshots are already there: https://f-droid.org/en/packages/com.mbestavros.geometricweather/

I believe this can be closed?

**Comment by mondlicht-und-sterne** [comment]
Than can you close it

**Comment by papjul** [comment]
I can't, I'm not a maintainer of this project, but you are the author of the issue, you can close it.

**Comment by Korb** [comment]
Screenshots are still not showing up on the app page in F-Droid.
https://f-droid.org/packages/wangdaye.com.geometricweather/
![Screenshot_2023_0402_104400](https://user-images.githubusercontent.com/3509797/229339600-4a0f488e-5f62-4512-87a4-e24d620ee3ff.jpg)

**Comment by papjul** [comment]
Works fine on Droid-ify, it's either an issue with your custom repo or your F-Droid app. Please retry after removing the repo and you will know which one it is.

**Comment by Korb** [comment]
It is difficult to say in which repository the incorrect information about this application is distributed:

![Screenshot_2023_0402_132625](https://user-images.githubusercontent.com/3509797/229347473-b264dc3e-ac77-4a91-a720-abdbdcebe1c6.png)
![Screenshot_2023_0402_132743](https://user-images.githubusercontent.com/3509797/229347474-8b2c9f98-af2c-4075-8282-aad73a9111ed.jpg)

**Comment by papjul** [comment]
Your screenshot shows Julian's F-Droid repo
