### ISSUE TITLE
通知栏图标问题

### ISSUE THREAD

**Issue by EMLVIRUS** [WangDaYeeeeee/GeometricWeather#17]
Ver 5.3.0
[EMUI 5.0 (Android 7.0) on HUAWEI NXT-AL10]
当通知栏内的常驻通知图标为晴天的太阳图标时，显示为白色方块（即无法识别显示）
未知是否为系统自身bug但有别的显示正常的应用（如微风）

**Comment by WangDaYeeeeee** [comment]
我研究一下吧

**Comment by EMLVIRUS** [comment]
系统更新后已消失
