### ISSUE TITLE
[Feature Request] Manually adding location

### ISSUE THREAD

**Issue by DealsBeam** [WangDaYeeeeee/GeometricWeather#171]
I understand it states that there is currently no way to do this, but this is a must have - I don't have my location on all the time because it drains battery, I'm sure other users are the same.

This feature needs to be implemented some how, it would be greatly appreciated.

**Comment by WangDaYeeeeee** [comment]
Click the building icon in the upper-right corner of the main interface, then you will enter the management page and you can search a location by clicking the search bar and input its name.
