### ISSUE TITLE
Accuweather API getDaily and getHourly uses metric, no option to change to imperial

### ISSUE THREAD

**Issue by RayG96** [WangDaYeeeeee/GeometricWeather#172]
Currently it uses metric all the time, setting to be able to switch to imperial would be nice.

![Screenshot_1](https://user-images.githubusercontent.com/52840114/106487426-a3b3e780-6480-11eb-8f2d-8f90e77ee1fd.jpg)

**Comment by WangDaYeeeeee** [comment]
I will try to fix it.
