### ISSUE TITLE
希望可以在每日概览中添加入昨日的气温

### ISSUE THREAD

**Issue by dawnlau** [WangDaYeeeeee/GeometricWeather#187]
![weather](https://user-images.githubusercontent.com/18576116/110921768-e3140480-8359-11eb-82d7-83d4783afa4a.jpg)

如图，在今日左边加入昨日的温度，通过比较可以知道气温变化幅度，指导穿衣。

感谢！

**Comment by WangDaYeeeeee** [comment]
昨日天气是有的，一般来说，这个要看数据源，如果数据源不提供昨日气温，会通过本地缓存的方式来实现，也就是说第二天才会显示数据，另外显示的格式是横线，不过我回复这么晚估计你也应该看到了...最近几天再准备阿里和字节的面试，所以一直没抽出时间来处理

**Comment by dawnlau** [comment]
嗯嗯，面试顺利哈！
