### ISSUE TITLE
Wrong notification values

### ISSUE THREAD

**Issue by RemyL** [WangDaYeeeeee/GeometricWeather#195]
I use the "tomorrow weather forecast" notification.
However today i noticed that the "day" value is not the same than the app show me for tomorrow (the "night" value seems ok)
Actually it seems to show "today day" value instead of "tomorrow day" value

I use mf provider

Edit:
I'm now sure that the tomorrow forecast notification is displaying "today day" value instead of "tomorrow day" value.
Moreother thie issue is not linked to providers because i get same issue with mf provider and accuweather provider

**Comment by WangDaYeeeeee** [comment]
Got it~ and I'll check that.

**Comment by RemyL** [comment]
I won't open a PR myself because i'm not sure and i have no time to build the app again.
I think that the issue can be easily solved in this file:
 GeometricWeather/app/src/main/java/wangdaye/com/geometricweather/remoteviews/presenters/notification/ForecastNotificationIMP.java 

By replacing 0 by 1 in line 115
