### ISSUE TITLE
Navigation Drawer 划开时，左上角的汉堡图标不应该变成三角

### ISSUE THREAD

**Issue by xingrz** [WangDaYeeeeee/GeometricWeather#2]
如题，这是很大部分人对 Navigation Drawer 的一个误用。

**Comment by DanteAndroid** [comment]
怎么说？论据是？

**Comment by xingrz** [comment]
虽然 Google Design Spec 里面没有明确说明这个，但 Google apps （如 Play Store）可以佐证。

事实上 `ActionBarDrawerToggle` 是 4.X 时期 Holo Design 的产物。在 Holo Design 以及 Material Design 初期，Navigation Drawer 是在 Action Bar 底下的，所以划开 drawer 的时候 Action Bar 还在上方。

后来 Material Design 正式版时把 [Navigation Drawer](https://www.google.com/design/spec/patterns/navigation-drawer.html#navigation-drawer-content) 改到最顶层了，也就是说划开之后会覆盖住 Action Bar，也就没有改变 icon 的必要了。

因此直接在 navigation click 的时候打开 `.openDrawer` 即可，不需要使用 `ActionBarDrawerToggle` 了。

**Comment by DanteAndroid** [comment]
好像确实如此。旧版的知乎也用了汉堡动画，现在想想确实没必要。谢谢指教。
