### ISSUE TITLE
Live Icon Size

### ISSUE THREAD

**Issue by vajiralasantha** [WangDaYeeeeee/GeometricWeather#21]
Hi, 
Can you please tell me how to increase the size of live weather icon? 

I changed `<dimen name="live_weather_icon_size">100dp</dimen>` but when I enter around 125dp, the icon is cropped from right and bottom sides. I want to add a large icon like 150dp.

Please help.

Other than that, thanks a lot for this amazing app.

**Comment by WangDaYeeeeee** [comment]
Will, I think you'd better not increase the size. If you increase the size, there might be a problem in UI widget when it measure layout.

If you are using a large-size device, I can tell you that I will make Geo Weather support the large-size device.

**Comment by vajiralasantha** [comment]
Oky I'm keeping it to 100dp for now. Otherwise icon is too small on larger phones.

Is it possible to add another location tracking lib for this other than Baidu? Because it fails to locate GPS when I run this on emulators with GPS enabled.

**Comment by WangDaYeeeeee** [comment]
I will try, but not in next version. After that, I have some work to do.

**Comment by vajiralasantha** [comment]
I have already added location search using Google Play API and maps API to resolve current address as well.
