### ISSUE TITLE
Not avaliable at Google Play

### ISSUE THREAD

**Issue by fm-sys** [WangDaYeeeeee/GeometricWeather#212]
Today I stumbled over this really nice open source project and wanted to download it via Google Play, but it just shows that the app isn't available anymore. What happened?

**Comment by WangDaYeeeeee** [comment]
It has been removed because there are some unsafe code in AMAP location SDK, and I've already removed this SDK for GooglePlay platform and published a new update. I think it will be reviewed and available soon.
