### ISSUE TITLE
Day/date language translation

### ISSUE THREAD

**Issue by DanRotaru** [WangDaYeeeeee/GeometricWeather#213]
In widgets (even if I set app language to another), day, month name is always in English. 
In app translation works fine.
![IMG_20210415_000946](https://user-images.githubusercontent.com/7759507/114779766-30332e00-9d7f-11eb-99fa-40bfef1853d6.jpg)
Choosen language in settings
![Screenshot_2021-04-15-00-13-14-97_34117015f116690223ec8511b30117a0](https://user-images.githubusercontent.com/7759507/114779943-6375bd00-9d7f-11eb-97ff-090e91ae2d09.jpg)

**Comment by WangDaYeeeeee** [comment]
Actually, since the special mechanism of app widgets, the option of language in GeoWeather app cannot work on the date text of widgets. So if you want it to show another language, you need to change the language in System Settings or your Launcher's Settings. That might be work.
