### ISSUE TITLE
French translation : improve weather warning

### ISSUE THREAD

**Issue by breversa** [WangDaYeeeeee/GeometricWeather#234]
Hi there french translators !

With the current lousy weather, I often get warnings like this one :

![Screenshot_20210518-141758_Omega_Launcher](https://user-images.githubusercontent.com/2071276/118655288-b19c3700-b7e9-11eb-9369-9f43b6e720d4.png)

As you can see, several things could be improved :

- The big space between "`prévus,`" and "`(ex. mistral`"
- Semi-colons where other punctuation marks would be better
- (lack of) spacing before punctation marks

**Comment by papjul** [comment]
Salut, le bulletin météorologique est édité par Météo France (et va varier si tu changes de fournisseur météo), il n'y a rien qu'on peut faire du côté de l'application ;)

**Comment by papjul** [comment]
In English: this is not a translation issue but an issue on weather provider side.

**Comment by breversa** [comment]
Damn that's an ugly job, Météo France ! :open_mouth:
