### ISSUE TITLE
Openweathermap and Yahoo APIs

### ISSUE THREAD

**Issue by vajiralasantha** [WangDaYeeeeee/GeometricWeather#24]
Any plan for adding support for openweathermap or Yahoo APIs?

**Comment by WangDaYeeeeee** [comment]
Nope not yet...

The rate limit of those two API are too few.

**Comment by dimqua** [comment]
Is OpenWeatherMap's 60 calls/min. too few?

**Comment by vajiralasantha** [comment]
It's not. I will look into that. Only thing is mapping data into current weather data models will not be easy.

**Comment by WangDaYeeeeee** [comment]
There may be some time, app request too much times weather data from API.
