### ISSUE TITLE
[Feature request] support customized Openweathermap API 

### ISSUE THREAD

**Issue by denholm0hsun** [WangDaYeeeeee/GeometricWeather#250]
It's necessary for people who choose OWM as the data source to use their own OWM APIs. Or The OWM data is always unusable. 
Geometric Weather is nice and I hope it become a first choice among many softwares of same type. Thank you!

**Comment by papjul** [comment]
Do you mean "custom API key"?
We already have #224 for this.

**Comment by denholm0hsun** [comment]
> Do you mean "custom API key"?
> We already have #224 for this.

Thank you, but I couldn't find the "advanced service provider setting"

**Comment by papjul** [comment]
Next version will have it ;)

**Comment by denholm0hsun** [comment]
> Next version will have 

> Next version will have it ;)

I see, have a good day, friend😏
