### ISSUE TITLE
Have transparent widgets

### ISSUE THREAD

**Issue by legacychimera247** [WangDaYeeeeee/GeometricWeather#262]
Althought the app is already beautiful as it is, it would be nice to have transparent widgets, not only black and white

This is an example of another app that does it quite well, so you know what i mean...
![Screenshot_20210823-162845](https://user-images.githubusercontent.com/22254556/130465410-84e582d0-73f1-4144-ba22-c6cf6a6c4092.png)

**Comment by Geeyun-JY3** [comment]
Actually you can set the widget Background color as None. Then it would be transparent.

**Comment by Geeyun-JY3** [comment]
Just add the widget to home screen then the setting panel would pop up.

**Comment by OliverLew** [comment]
I think OP means the cards in the app, not the widgets added to the home screen. Currently, we could only change the card background by choosing a bright or dark theme.

If that's the case, maybe the title can be modified to describe the issue more accurately.

**Comment by papjul** [comment]
This is not possible without redesigning the whole design. The app you're showing is rather dull (no icons, no color variations, no bright colors). For example, with the current GW design, if you make a transparent background, how can you show the sun icon on top of a sunny background?

I suggest you use the app with the design you like. To achieve the same result in GW, we would need to remove a lot from the current design and Geometric Weather would not be Geometric Weather anymore.
