### ISSUE TITLE
Provider Issue

### ISSUE THREAD

**Issue by Diamantitos2** [WangDaYeeeeee/GeometricWeather#292]
When i put as provider OpenWeather. The weather in general doesnt work
![image](https://user-images.githubusercontent.com/86315038/153985792-47e3eb1d-5794-4339-a3ac-a57273db19ef.png)
![image](https://user-images.githubusercontent.com/86315038/153985815-6c3c47ac-2755-4451-9de2-fa090ffff6e9.png)

**Comment by WangDaYeeeeee** [comment]
There is a strict limitation on the number of requests on my OpenWeatherMap API key, so you will find that requests often fail. You can add your own API key on the settings page, or switch to the Accu weather source, which can be used stably
