### ISSUE TITLE
[Feature Request] Support Material You

### ISSUE THREAD

**Issue by theuser18** [WangDaYeeeeee/GeometricWeather#295]
Android 12 comes with [Material You](https://material.io/blog/start-building-with-material-you), a theming engine that dynamically changes the color or certain parts of apps. Having this integrated with Geometric Weather and its widgets would be fantastic!

**Comment by WangDaYeeeeee** [comment]
I'm already started work on it. And currently, the dynamic color is already usable in the dev branch.

**Comment by radical4ever** [comment]
Amazing!. Do You have an apk to try on my phone?

**Comment by papjul** [comment]
You can download the latest beta from the Releases page, or from F-Droid.

**Comment by radical4ever** [comment]
> You can download the latest beta from the Releases page, or from F-Droid.

Got it and thanks!
