### ISSUE TITLE
添加生活指数

### ISSUE THREAD

**Issue by xuangeyouneihan** [WangDaYeeeeee/GeometricWeather#297]
如题，就是这部分。谢谢开发者！  
![Screenshot_20220331_103407_org bromite bromite_edit_402790569629163](https://user-images.githubusercontent.com/50788434/160965443-cd7f86a1-d8d7-4e07-991f-e264307aa431.jpg)

**Comment by WangDaYeeeeee** [comment]
短期内应该不会添加...近期没有换数据源的打算，现有数据源是没有这些数据的
