### ISSUE TITLE
[3.100] Placeholder no longer shown in advanced provider settings

### ISSUE THREAD

**Issue by papjul** [WangDaYeeeeee/GeometricWeather#298]
This code no longer exists:
https://github.com/WangDaYeeeeee/GeometricWeather/blob/cf0b1a6a5cbb9ab1d27cf29879ecb4c11f2f16bd/app/src/main/java/wangdaye/com/geometricweather/settings/fragments/ServiceProviderAdvancedSettingsFragment.java#L40-L50=

![image](https://user-images.githubusercontent.com/1449159/165494523-347a7447-2a55-4a0f-b5d1-cfc4c463fd8b.png)

It used to show "Default (unchanged)" in custom API keys fields.

This placeholder is useful to indicate to the user that he can leave the field empty so the default key applies instead of the customized one.

**Comment by WangDaYeeeeee** [comment]
You're right, I'm gonna fix it.
