### ISSUE TITLE
Custom MeteoFrance API key

### ISSUE THREAD

**Issue by farfromrefug** [WangDaYeeeeee/GeometricWeather#313]
Hi, may i ask where you got your meteofrance apikey? And where is the doc for their API?

I would like to use my custom key
Thanks

**Comment by papjul** [comment]
I don't remember, I think it's the default key used for basic calls (which are free for visitors)? I added the ability to customize the API key in case it would stop working, but you should not need it currently.

There used to be a public API documentation but I can't find it anymore. It seems it's now replaced by https://partner-api.meteofrance.com/ but the documentation only covers two APIs (there are many more) and not the basic ones we use here (which I remember reading the documentation on a similar website). Maybe if you register, you can see more. Advanced APIs are also subject to fees, which are way too expensive even for an association, according to some hobbists I talked to.

**Comment by farfromrefug** [comment]
@papjul thanks for the details! I ll try to dig a bit more
