### ISSUE TITLE
Widget and app always show night

### ISSUE THREAD

**Issue by mattvchandler** [WangDaYeeeeee/GeometricWeather#331]
For the last couple of days, the widget icon and app background are always showing partly cloudy night, even when it is midday. All of the data displayed is still correct, even the current condition which says "Partly sunny". I checked the website for my city for my provider (AccuWeather), and it is accurately showing daytime conditions.

This problem persists across reboots, and reinstallation of the app.

![Screenshot_20220531-075120_Geometric Weather](https://user-images.githubusercontent.com/1538163/171218833-807f4296-fc87-4029-8c2e-80c590248116.png)

Since this started a few days ago and worked fine before, and since there hasn't been an update in that time, my guess is that the app is struggling with the far northern latitude long summer days (we're currently at about 20hrs)

**Comment by WangDaYeeeeee** [comment]
Could you provide your current location and the dark mode option in the settings page of the GeometricWeather app?

**Comment by mvchandler** [comment]
Fairbanks, Alaska, but I'm seeing the same issue in other locations around or above the same latitude.
The dark mode is set to 'Follow System', but in the image above, the light theme is being used.
I should add that it's not showing the clouds today (not it's showing the 'starry night' animation within the app and the moon icon on the widget), so it does seem to be reading some of the weather status, it's just doesn't seem to realize that it's day.

**Comment by WangDaYeeeeee** [comment]
I've already fixed this bug. And I will release a new version of GeometricWeather app soon.
