### ISSUE TITLE
In 3.101 RU translation is not updated

### ISSUE THREAD

**Issue by Denio-7** [WangDaYeeeeee/GeometricWeather#342]
In GeometricWeather/app/src/main/res)/values-ru files are not updated, although pull requests 320 & 321 are implemented in 3.101.

Wang, i also sent you these files and about some bugs on Gmail as ususal, but you're not answering, seems you're too busy.

**Comment by WangDaYeeeeee** [comment]
Let me check that...And yes, I am a little bit busy with the matters related to my master's graduation these days btw.

**Comment by Denio-7** [comment]
I'm well aware of that, I keep my fingers crossed for a successful outcome ;-).
