### ISSUE TITLE
[Suggestion] Add Apple's new provider

### ISSUE THREAD

**Issue by userNeptune** [WangDaYeeeeee/GeometricWeather#353]
Apple has long acquired DarkSky now provides a new weather service, Consider adding to GW

WeatherKit is powered by the all-new Apple Weather service
https://developer.apple.com/weatherkit/

**Comment by d4f5409d** [comment]
Yes! It would be awesome!

**Comment by papjul** [comment]
This is the GitHub repo for the Android project, you probably want to open an issue here: https://github.com/WangDaYeeeeee/GeometricWeather-iOS/issues

**Comment by d4f5409d** [comment]
WeatherKit is an API. It is possible from Android to access it.

**Comment by papjul** [comment]
Sure, but you need an Apple Developer account to subscribe (which is not free, as far as I understand). I'm not sure a regular Android user have this kind of account. So unless an Apple Developer wants to step in to implement Weather Kit in the Android version and make sure it works by testing with their API key...

**Comment by d4f5409d** [comment]
It's not so important.
