### ISSUE TITLE
Restart button within application does not restart application.

### ISSUE THREAD

**Issue by jdev082** [WangDaYeeeeee/GeometricWeather#355]
**Software Specifications:**
Android 11.0
Google Security Patch Level: May 2022
Google Play System Update: May 2022
Geometric Weather: 3.013

**Bug**
Upon changing a configuration option, such as mode or UI style. At the very bottom, a popup telling me to restart the software while also providing a restart button appears. Upon pressing said restart button, the app seemingly flashes and doesn't restart fully. Causing the change to not be made.

**Affected Components**: Geometric Weather

**Comment by papjul** [comment]
I would suggest updating to version 3.102 first, your version is more than a year old. Let us know if you can reproduce then, and add screenshots, and if possible, a recording.

**Comment by jdev082** [comment]
> I would suggest updating to version 3.102 first, your version is more than a year old. Let us know if you can reproduce then, and add screenshots, and if possible, a recording.

UI style option not available in this release, cannot reproduce issue.

**Comment by papjul** [comment]
Yes, I think it fixes more issues than it adds, though. I use master branch with no issues for a year.
You may need to remove any widget you have before updating, as some crashes were reported, or clear data in the worst case.

**Comment by jdev082** [comment]
> Yes, I think it fixes more issues than it adds, though. I use master branch with no issues for a year. You may need to remove any widget you have before updating, as some crashes were reported, or clear data in the worst case.

I'm not really a user of widgets anyway, the one widget I use is Moto Widget and that's about it. If anything bad were to happen, I would have the skill to fix it.
