### ISSUE TITLE
Implement Serenum privacy respecting weather service

### ISSUE THREAD

**Issue by d4f5409d** [WangDaYeeeeee/GeometricWeather#363]
https://serenum.org/

**Comment by papjul** [comment]
What's the difference between:
Geometric Weather > Serenum > OpenWeather
Geometric Weather > OpenWeather
?

I couldn't find anything on the website that would justify a higher privacy level from what we do currently with OpenWeather.

It seems to me that you're adding an extra unneeded step that would require extra maintenance in Geometric Weather while providing the same weather data and privacy level.
