### ISSUE TITLE
Confusing F-Droid settings

### ISSUE THREAD

**Issue by julianfairfax** [WangDaYeeeeee/GeometricWeather#388]
Can the Baidu options be entirely removed from the settings on the F-Droid version? I thought the options saying only for China meant it just wouldn't work elsewhere. But the F-Droid description says it's not supported at all. This is confusing. It would be easier to understand if they weren't options.

For this reason, can Baidu be removed from the weather source list and the advanced service provider settings, and can the location provider setting be removed entirely? Only on the F-Drois build of course. Thank you for developing this app!

**Comment by papjul** [comment]
And why would you exclude people living in or traveling to China from the F-Droid version?

**Comment by julianfairfax** [comment]
> And why would you exclude people living in or traveling to China from the F-Droid version?

They aren't. But the description of the F-Droid version says that those options do not work. That is why it's confusing.

**Comment by papjul** [comment]
Where do you see that? https://github.com/WangDaYeeeeee/GeometricWeather/blob/master/fastlane/metadata/android/en-US/full_description.txt

You're talking about Baidu IP location, right?

**Comment by julianfairfax** [comment]
> Where do you see that? https://github.com/WangDaYeeeeee/GeometricWeather/blob/master/fastlane/metadata/android/en-US/full_description.txt
> 
> You're talking about Baidu IP location, right?

https://github.com/WangDaYeeeeee/GeometricWeather/blob/master/fastlane/metadata/android/en-US/full_description.txt#L16-L19 and yes

**Comment by papjul** [comment]
This is a list of weather providers. Baidu IP location is not a weather provider, hence why it's not listed here. It's a location service, as you can see in the settings where you found the option.

**Comment by julianfairfax** [comment]
Oh yes, caiyunapp.com is the weather source. But that is also not in the list.
