### ISSUE TITLE
Option to disable automatic refresh

### ISSUE THREAD

**Issue by lokesh-krishna** [WangDaYeeeeee/GeometricWeather#39]
Could you please consider adding an option to disable the automatic refresh rate? Maybe by letting the user set it to 0.

**Comment by WangDaYeeeeee** [comment]
Sorry to replay to you so late, buddy.

Is that option really necessary? If you check background free option, there will be no resident services in the background.

**Comment by lokesh-krishna** [comment]
I'm sorry. I didn't realize that's what that option did. That makes this issue redundant.
