### ISSUE TITLE
Add bft scale

### ISSUE THREAD

**Issue by efb4f5ff-1298-471a-8973-3d47447115dc** [WangDaYeeeeee/GeometricWeather#397]
https://en.wikipedia.org/wiki/Beaufort_scale

Should be displayed as 

0 bft - calm
1 bft - Light air
2 bft - light breeze
...

**Comment by papjul** [comment]
Geometric Weather already uses the BFT scale:
https://github.com/WangDaYeeeeee/GeometricWeather/blob/master/app/src/main/java/wangdaye/com/geometricweather/common/basic/models/weather/Wind.java#L28-L39

And here is the translation file:
https://github.com/WangDaYeeeeee/GeometricWeather/blob/master/app/src/main/res/values/strings.xml#L79-L91

Let us know of any mistake!

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
It only says gentle breeze and doesnt display 1,2,3,4...11

It is not possible to configure this in the settings

I want to select bft in the settings and the graphs and the stats to say 1 or 2...11

![Screenshot_20220811-090623.png](https://user-images.githubusercontent.com/73130443/184081066-4b0ba8ed-ae7d-413f-bb36-d79c6febab8a.png)![Screenshot_20220811-090553.png](https://user-images.githubusercontent.com/73130443/184081070-971778e0-c6f1-416b-97b4-8a15801ffa63.png)![Screenshot_20220811-090520.png](https://user-images.githubusercontent.com/73130443/184081087-a319d4d4-7e9f-429b-a152-90ebae325191.png)![Screenshot_20220811-090411.png](https://user-images.githubusercontent.com/73130443/184081094-708a4242-be50-4bfc-8d6c-b4df94b48e43.png)

**Comment by papjul** [comment]
You're showing the unit settings. BFT is a scale not an unit, there can't be conversion between them.

While you can "deduce" a BFT from a km/h, you can't do the opposite (convert a BFT into km/h).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Ok i understand but it would be nice somehow to only show thw bft in the graphs and stats

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
@papjul i dont want do come over as an annoying user that keeps asking about their issue (believe me i know how that feels like) but is there a possibility this could make its way into Breezy Weather?
