### ISSUE TITLE
这个锁屏通知怎么触发的？

### ISSUE THREAD

**Issue by Saszr** [WangDaYeeeeee/GeometricWeather#41]
如题

**Comment by WangDaYeeeeee** [comment]
e....有图么

**Comment by saszr** [comment]
嗯，我已经搞懂了。
-----------------------------------------------------------------
我是安卓8.0的，首先安卓系统设置里锁定屏幕偏好设置里，配置通知里有个“在锁定屏幕上保留通知” ，打开会一直显示通知栏里的通知（直接在锁屏面显示，比如天气就直接在锁屏面显示），关闭只会显示新的通知（看常驻的通知，锁屏面下拉）。     
我这个配置是关闭的，然后锁屏，下拉会显示通知栏里的天气通知。这个软件设置里那个隐藏锁屏通知，如果勾选了，下拉就不会显示了。（当然你配置是开启的，勾选了当然也不会显示）
-----------------------------------------------------------------
我提这个问题是，有时候我会直接在锁屏面看到天气的通知，有时候不会，所以提了这个问题。
不过今天我看了下系统设置，明白了，这个应该是后台刷新了天气，正好我锁屏，是一个新的通知，所以直接就直接在锁屏面出现了。
-----------------------------------------------------------------
说的有些绕，哈哈哈
