### ISSUE TITLE
Misaligned city in widget

### ISSUE THREAD

**Issue by hurried6158** [WangDaYeeeeee/GeometricWeather#442]
![Screenshot_20221226-132050](https://user-images.githubusercontent.com/121438152/209549032-49caec7b-1572-40f1-b506-431f0d7e2668.png)

Milan is misaligned here. Should be aligned to the right.

I'm using the KISS launcher which might be impacting this?

**Comment by fookinhell** [comment]
I have exactly the same issue, using the same launcher !

**Comment by hurried6158** [comment]
This was seemingly a bug in the KISS launcher since the problem has disappeared in the latest version
