### ISSUE TITLE
A few issues I encountered 

### ISSUE THREAD

**Issue by CattopyTheWeb** [WangDaYeeeeee/GeometricWeather#480]
- The app isn't available on the Google Play store. When I click the link, it says unknown app.
- Why does my location's weather warning in Chinese??? But when I manually enter my location, it is normal English.
- How do I remove the location so that I only have the location I entered manually? I don't see any button

So there are all the issues I encountered so far. If you could help me fix them that would be great.

**Comment by papjul** [comment]
> * The app isn't available on the Google Play store. When I click the link, it says unknown app.

Please check existing issues.

> * Why does my location's weather warning in Chinese??? But when I manually enter my location, it is normal English.

Screenshot please.

> * How do I remove the location so that I only have the location I entered manually? I don't see any button

On the location list page, slide from left to right on the location to remove.

**Comment by CattopyTheWeb** [comment]
Now that I removed that my location in Chinese. It's all good. Thanks

**Comment by CattopyTheWeb** [comment]
Btw This app is great! I like the UI
