### ISSUE TITLE
Black chemical compounds in dark theme 

### ISSUE THREAD

**Issue by HotarunIchijou** [WangDaYeeeeee/GeometricWeather#482]
![](https://github.com/WangDaYeeeeee/GeometricWeather/assets/113282550/cb6bab35-470a-4314-957c-933cbb170dfd)
It's pretty unreadable

**Comment by HotarunIchijou** [comment]
It seems to be fixed, so I close the issue

**Comment by papjul** [comment]
It's fixed on my fork, you can test a debug version in #440 (artifact in Checks tab).

**Comment by HotarunIchijou** [comment]
Yes, I've already downloaded debug version from actions
