### ISSUE TITLE
The degree icon is too far from the numbers

### ISSUE THREAD

**Issue by HotarunIchijou** [WangDaYeeeeee/GeometricWeather#483]
![](https://github.com/WangDaYeeeeee/GeometricWeather/assets/113282550/3d53cc06-e62c-4d7f-b72d-a3ac661dc32f)

**Comment by papjul** [comment]
How do you enter this display mode?
Do you have a step-by-step?

The spacing between the number and its unit is correct, however I can see it's missing Celsius or Fahrenheit, and a yellow round shape is overlapping the temperature, so I would like to check.

**Comment by HotarunIchijou** [comment]
It's a widget. To get it, you should:
1. Long press to your home screen
2. Select widgets
3. Look for Geometric Weather
4. Choose Material You - Current

Here's also a comparison with google weather widget, I think it should look more like this
![](https://github.com/WangDaYeeeeee/GeometricWeather/assets/113282550/e25b0248-7bc6-461f-b15c-3ad659b57606)
Google weather widget - left, Geometric weather widget - right

I also noticed that the borders of the widget are too big, you can see it below
![](https://github.com/WangDaYeeeeee/GeometricWeather/assets/113282550/8acde62f-2f10-481f-9853-6b9d9e06d752)

**Comment by HotarunIchijou** [comment]
I noticed that on other widgets the degree icon is also too far from numbers

**Comment by papjul** [comment]
Ok, so the overlapping is normal if the reference is the Google Weather widget.

Regarding the spacing, the Google widget is wrong, as per SI conventions, there is a spacing between a number and its unit, so nothing wrong on Geometric Weather side ;)

**Comment by papjul** [comment]
I removed the spacing when ° is alone, but not when written °C or °F. Best would be to always show °C or °F, as 30° makes no sense if you don't say the unit you're using. But as it is commonly used everywhere and we have limited space, let's keep it that way.

**Comment by HotarunIchijou** [comment]
But how about borders of the widget?

**Comment by papjul** [comment]
> But how about borders of the widget?

I checked the code and I have no idea. I don't use widgets, I only have a Quick Settings tile to check the current weather.

**Comment by HotarunIchijou** [comment]
Ok. But I think that the previous position of numbers was better, because now the right angle nearby circle looks isn't really good

**Comment by papjul** [comment]
> Ok. But I think that the previous position of numbers was better, because now the right angle nearby circle looks isn't really good

I didn't change the position, can you make a screenshot to point the issue?

**Comment by HotarunIchijou** [comment]
Of course
![](https://github.com/WangDaYeeeeee/GeometricWeather/assets/113282550/8d83d5a5-c58b-4868-9248-8b4d1e2a148d)

**Comment by papjul** [comment]
Can you draw on the screenshot? The issue is not obvious to me, I don't understand what is the "right angle".

**Comment by HotarunIchijou** [comment]
![](https://github.com/WangDaYeeeeee/GeometricWeather/assets/113282550/13d638d5-4191-4c90-ae7e-927214c21bb8)
Look at bottom of the number "2"
