### ISSUE TITLE
update

### ISSUE THREAD

**Issue by senolfndk** [WangDaYeeeeee/GeometricWeather#501]
when is the new update

**Comment by meenbeese** [comment]
Geometric Weather is not maintained, but you can check our new and actively developed fork: [Breezy Weather](https://github.com/breezy-weather/breezy-weather).

**Comment by senolfndk** [comment]
> Geometrik Hava Durumu korunmaz, ancak yeni ve aktif olarak ayrılabilir çatalımızı kontrol edebilirsiniz: [Breezy Weather](https://github.com/breezy-weather/breezy-weather) .

ok
