### ISSUE TITLE
无法自动刷新

### ISSUE THREAD

**Issue by linsui** [WangDaYeeeeee/GeometricWeather#54]
无法自动刷新天气。点击小部件也不起作用。另外希望可以通过小部件进入应用。
rom：小米6 PixelExperience Android 9

**Comment by WangDaYeeeeee** [comment]
在多任务界面中把app锁定了么？国内ROM的话，如果app在多任务界面被划掉或者未上锁（加入白名单）被ROM进行资源回收，一切后台任务都会被清除而且在app被再次打开之前无法开启

**Comment by linsui** [comment]
我用的是原生rom，而且即使进入应用也不会自动刷新。预警可以正常推送，应该没有被清理

**Comment by linsui** [comment]
更新版本之后后台纯净可以关闭了。之前无法关闭

**Comment by linsui** [comment]
我关掉了后台纯净。然后关闭了后台通知权限，现在可以自动刷新，而且没有后台通知:joy: 谢谢
