### ISSUE TITLE
Feature Request - OpenWeatherMap Support

### ISSUE THREAD

**Issue by Olika120** [WangDaYeeeeee/GeometricWeather#55]
It would be really good if the app supported OpenWeatherMap, as its open, easy to get an API key for, and accurate. In Hungary(where i live) OpenWeatherMap is the only weather provider that gives good data about the weather.

**Comment by WangDaYeeeeee** [comment]
Sorry to reply to you so late, OpenWeatherMap will be an important part of the next version, but it may take some time, recently I was preparing for the postgraduate exam and didn't have much time to code.

**Comment by Olika120** [comment]
Thanks for the reply! No problem, good luck with your exam!

**Comment by UnsolvedCypher** [comment]
Is this still in the works? Is there any help you would like with this?
