### ISSUE TITLE
App constantly crashes

### ISSUE THREAD

**Issue by infinitewaveparticle** [WangDaYeeeeee/GeometricWeather#56]
I'm using version 2.113 on Android 8.1 - Galaxy S7 Edge. The app works and successfully connects and gets data, but it crashes constantly. I have monitored my network traffic and there are no problems there. The app just crashes for seemingly no reason - while running in either the background AND foreground. I currently can't even open the main window to change options.

**Comment by WangDaYeeeeee** [comment]
I will push a new version soon. Maybe in tomorrow.
