### ISSUE TITLE
[feature request] 保留昨天的天气

### ISSUE THREAD

**Issue by WanderMax** [WangDaYeeeeee/GeometricWeather#59]
能否增加一个保留昨天天气的功能，这样知道天气的相对变化

**Comment by vivaxy** [comment]
请问昨日天气是否有了？

**Comment by WangDaYeeeeee** [comment]
有昨日温度，天气的话感觉没特别大的必要吧。。。昨天刮风还是下雨的话，印象应该很强的才对

vivaxy <notifications@github.com> 于2019年10月15日周二 上午8:24写道：

**Comment by vivaxy** [comment]
![image](https://user-images.githubusercontent.com/4216856/66792785-e28cf980-ef2c-11e9-986d-e8b072348437.png)

@WangDaYeeeeee 图中没有看到合理的昨日温度，请问哪里可以看到昨日温度？

**Comment by WangDaYeeeeee** [comment]
折线图里的横线

vivaxy <notifications@github.com> 于2019年10月15日周二 上午9:21写道：
