### ISSUE TITLE
Feature Request - An option to set your own API key inside the settings

### ISSUE THREAD

**Issue by OliverParoczai** [WangDaYeeeeee/GeometricWeather#67]
If you are working on making the app available on F-Droid, an option to specify your own API keys inside the app is a must have.

**Comment by Olika120** [comment]
Yeah, but if this gets to F-Droid, a lot more people will use it and if they need to recompile the app to change the API key they will probably stick to the original keys, thus after a lot of users the api key will be limited or blocked. Also, that feature request is also made by me. :)
