### ISSUE TITLE
F-Droid

### ISSUE THREAD

**Issue by Jiack214** [WangDaYeeeeee/GeometricWeather#9]
This app cannot be included into F-Droid due to binaries (liblocSDK7.so, BaiduLBS_Android.jar) with unclear license.
Is it possible to remove/replace them in some way?

**Comment by WangDaYeeeeee** [comment]
I cannot remove them, it is the location widget. 
As I know, the license will write some log and update them, but I didn't request the write permission for them, so the license can do nothing, except location.

**Comment by dimqua** [comment]
Can them be replaced somehow?

**Comment by WangDaYeeeeee** [comment]
Well, I will try that, but not now. After that, I have some work to do.

**Comment by picsi** [comment]
@rudloff we now have a proper build flavor, might be good to give this a go

**Comment by Rudloff** [comment]
Are you sure? It seems https://github.com/WangDaYeeeeee/GeometricWeather/pull/38 was not merged.

**Comment by lionirdeadman** [comment]
So.. Any news on this?

**Comment by dimqua** [comment]
https://apt.izzysoft.de/fdroid/index/apk/wangdaye.com.geometricweather

**Comment by lionirdeadman** [comment]
This still contains Baidu and the other non-free software to my knowledge.

**Comment by IzzySoft** [comment]
As there's still no FOSS build flavor (the corresponding PR was closed instead of merged), and the underlying issues are still unsolved after 2 years, I'll for now [close the request](https://gitlab.com/fdroid/rfp/issues/22) to include it at F-Droid. @WangDaYeeeeee please update this issue once you're ready, so I can reopen the issue on our end.

**Comment by Neurognostic** [comment]
Any update on making this application [F-Droid compliant](https://f-droid.org/en/docs/Inclusion_Policy/)? It's a beautiful weather application you have made and it would be great if it could be built without the tracking and non-free dependencies.

https://f-droid.org/en/contribute/
https://f-droid.org/en/docs/Inclusion_Policy/
https://gitlab.com/fdroid/fdroiddata/blob/master/CONTRIBUTING.md
https://f-droid.org/docs/Submitting_to_F-Droid_Quick_Start_Guide/

Have you found any alternative providers for location? Or can you provide a branch which does not have the non-free dependencies?

**Comment by mbestavros** [comment]
I'm also interested in an F-Droid version without binary dependencies.

@dimqua @WangDaYeeeeee Is there any downside to just removing the Baidu options (plus whatever else those binaries provide) in an F-Droid branch? It seems unlikely Baidu services would be used on an F-Droid release anyway.

**Comment by mbestavros** [comment]
For those following this thread, I've gone ahead and done it myself: my fork of Geometric Weather removes all the proprietary blobs, so it should be fully FOSS.

This was a pretty primitive brute-force attempt that just rips out all code related to the Baidu APIs, but I'm happy to work with @WangDaYeeeeee, @dimqua, @IzzySoft or whoever to merge this if wanted. Regardless, I intend to update it upon new releases.

**Comment by IzzySoft** [comment]
@mbestavros thanks! As you intend to maintain the fork: maybe you could change the package name in yours (to avoid collision – cross-updates won't be possible anyway due to different signature), add [Fastlane file structure](https://gitlab.com/snippets/1895688), and then [apply for F-Droid inclusion](https://gitlab.com/fdroid/rfp/issues)? I'd pick up from there then. Of course I can also add your fork to my repo once the first 2 steps are done (and a new tag with APK is available), at least until it gets listed at F-Droid.org.

**Comment by mbestavros** [comment]
@IzzySoft Sounds good! I'll give it a try this weekend. I've created a tracking issue and sub-issues for both of your asks over on my repo: https://github.com/mbestavros/GeometricWeather/issues/3

**Comment by IzzySoft** [comment]
Now that Geometric Weather became available at F-Droid (congrats! :tada:) – shall I still keep it in my repo, @WangDaYeeeeee? Usually I remove it at this stage, unless explicitly requested otherwise, about 7..10 days after it became available at F-Droid. Just in case you want it to stay, I already adjusted my config here to

* pick the `*fdroid*.apk` (and not one of the others)
* use metadata provided via Fastlane (going into effect with the next sync tomorrow)

Next question is targeted at @mbestavros – you'll most likely discontinue your fork now, correct? So shall I add a corresponding note ("development returned to parent") and disable update checking?

**Comment by mbestavros** [comment]
@IzzySoft Yes, that is the plan! I have already updated all my documentation (including Fastlane descriptions and changelogs, and Github README) and threw up a pop-up on app open to direct to the new listing. I've tagged it, so hopefully it should go up soon.

What else can I do to help expedite the process?

**Comment by IzzySoft** [comment]
Wow, I guess that should cover it all. Just let me know when that version was "pulled", so we disable the update checks. As description etc. come via Fastlane, all else should already be in place. Thanks a lot!

**Comment by mbestavros** [comment]
@IzzySoft Thank you for all your help and guidance! I'm thrilled Geometric Weather is on F-Droid in full 🙂

**Comment by IzzySoft** [comment]
Not the least thanks to your hard work, if I might say so :wink:

**Comment by mbestavros** [comment]
Ah, well, credit where credit is due: the push to get F-Droid upstreamed was spearheaded primarily by @papjul, and he deserves most of the recognition 😄

**Comment by IzzySoft** [comment]
OK OK, did we mention everyone now – and does it finally stick? :rofl: Maybe we can give some of the cream to @WangDaYeeeeee as well? And of course everyone else involved… :tada: :partying_face:

**Comment by IzzySoft** [comment]
@mbestavros your latest build fails. I mean, it succeeds, but…

    ERROR: Could not build app com.mbestavros.geometricweather: Unexpected version/version code in output; APK: '2.610-foss' / '26100',  Expected: '2.610' / '26100'

Read: the `versionCode` from your `build.gradle` has a `versionSuffix` (`-foss`) which is not set up in the YAML and wasn't there before. Can be fixed either in the YAML (adding the suffix; not sure if one of our maintainers is already doing that) or via your `build.gradle` (removing the suffix).

**Comment by mbestavros** [comment]
@IzzySoft I will remove the suffix as a quick fix when I'm next at my computer.

Can I edit the current release on Github with the new changes, or should I tag a new release?

**Comment by IzzySoft** [comment]
As the build failed, both should be possible *at the moment* – if you want to make sure not to cross with any maintainer fixing the build, make a new tag. If the latter is an option for you, it's the safer variant.

**Comment by IzzySoft** [comment]
@mbestavros No change needed anymore, the [crossing just happened](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/8822)! So please do ***NOT*** touch the current tag – and no need for a new tag either.

**Comment by mbestavros** [comment]
@IzzySoft I'm just checking back on this now; I see that the Fastlane description of [my app](https://f-droid.org/en/packages/com.mbestavros.geometricweather/) has been updated, but the app itself is not new, so the in-app popup will not show. Should I still proceed with a new fixed tag to ensure the new app makes its way to users?

**Comment by IzzySoft** [comment]
As your build failed in the last run, the updated APK cannot yet be there as the fixed build would be in the current run (which is not yet completed – indeed, the [build just passed](https://monitor.f-droid.org/builds/log/com.mbestavros.geometricweather/26100) at 11:20am UTC today). So please wait for the next index, then check again.

**Comment by mbestavros** [comment]
@IzzySoft My [app listing](https://f-droid.org/en/packages/com.mbestavros.geometricweather/) seems like it got updated! I just downloaded the updated version and got the deprecation popup, so I think my fork is all set.

I think that wraps up everything we needed to do to get Geometric Weather released! 🎉

Last question: would it be okay for me to archive my fork, or does it need to stay live for F-Droid to work?

**Comment by IzzySoft** [comment]
I'd just [disabled auto-updates](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/8836), so it's fine to archive the repo. That way it remains accessible (even for F-Droid builds) while making clear there's no more development going on. Thanks a lot for "cleaning the table"!

**Comment by mbestavros** [comment]
@IzzySoft Perfect!! I will do so soon. And of course, I'm just trying to be a good open-source citizen 😄

**Comment by mbestavros** [comment]
@WangDaYeeeeee @Jiack214 Given Geometric Weather is now fully in F-Droid, I think it's probably appropriate to close this issue!

**Comment by IzzySoft** [comment]
Btw: with Geometric Weather now listed at "F-Droid proper", guess I can remove it from my repo after the usual overlap (~10d) – or is there demand that I shall keep it?

**Comment by IzzySoft** [comment]
Well, I've asked twice and got no protest, so I'll remove it from my repo. If needed, it can easily be restored, just let me know.

**Comment by Jiack214** [comment]
Thank you all!
